name: Build OpenList Package

on: 
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  Builds:
    uses: Internet1235/gh-action-sdk/.github/workflows/openwrt-builder.yml@sdk-go
    with:
      PACKAGE_NAME: 'openlist'
      tags: 'OpenListTeam/OpenList'
